package br.inf.ufes.vixcourts.persistence;

import javax.ejb.Local;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface AgendamentoDAO extends BaseDAO<Agendamento> {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Agendamento> buscarPorModalidade(Modalidade modalidade);
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Agendamento> buscarPorEndereco(Endereco endereco);
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Agendamento> buscarPorModalidadeEndereco(Modalidade modalidade, Endereco endereco);
	
}