package br.inf.ufes.vixcourts.entity;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Agendamento extends PersistentObjectSupport implements Comparable<Agendamento> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private DateTime HoraInicio;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private DateTime HoraFim;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private Usuario Source;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private Quadra Target;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToMany(mappedBy="Target")
		private Set<SolicitacaoJogo> Source;
		
	




	/** Getter for HoraInicio. */
	public DateTime getHoraInicio() {
		return HoraInicio;
	}
	
	/** Setter for HoraInicio. */
	public void setHoraInicio(DateTime HoraInicio) {
		this.HoraInicio = HoraInicio;
	}

	/** Getter for HoraFim. */
	public DateTime getHoraFim() {
		return HoraFim;
	}
	
	/** Setter for HoraFim. */
	public void setHoraFim(DateTime HoraFim) {
		this.HoraFim = HoraFim;
	}




		
		/** Getter for Source. */
		public Usuario getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Usuario Source) {
			this.Source = Source;
		}
		
	

		
		/** Getter for Target. */
		public Quadra getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Quadra Target) {
			this.Target = Target;
		}
		
	

		
		/** Getter for Source. */
		public Set<SolicitacaoJogo> getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Set<SolicitacaoJogo> Source) {
			this.Source = Source;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Agendamento o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}