package br.inf.ufes.vixcourts.entity;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Endereco extends PersistentObjectSupport implements Comparable<Endereco> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String Logradouro;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String Bairro;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private Integer CEP;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private Integer Número;

	/** TODO: generated by FrameWeb. Should be documented. */
	
	private String Complemento;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private Cidade Target;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToMany(mappedBy="Target")
		private Set<Quadra> Source;
		
	




	/** Getter for Logradouro. */
	public String getLogradouro() {
		return Logradouro;
	}
	
	/** Setter for Logradouro. */
	public void setLogradouro(String Logradouro) {
		this.Logradouro = Logradouro;
	}

	/** Getter for Bairro. */
	public String getBairro() {
		return Bairro;
	}
	
	/** Setter for Bairro. */
	public void setBairro(String Bairro) {
		this.Bairro = Bairro;
	}

	/** Getter for CEP. */
	public Integer getCEP() {
		return CEP;
	}
	
	/** Setter for CEP. */
	public void setCEP(Integer CEP) {
		this.CEP = CEP;
	}

	/** Getter for Número. */
	public Integer getNúmero() {
		return Número;
	}
	
	/** Setter for Número. */
	public void setNúmero(Integer Número) {
		this.Número = Número;
	}

	/** Getter for Complemento. */
	public String getComplemento() {
		return Complemento;
	}
	
	/** Setter for Complemento. */
	public void setComplemento(String Complemento) {
		this.Complemento = Complemento;
	}




		
		/** Getter for Target. */
		public Cidade getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Cidade Target) {
			this.Target = Target;
		}
		
	

		
		/** Getter for Source. */
		public Set<Quadra> getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Set<Quadra> Source) {
			this.Source = Source;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Endereco o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}