package br.inf.ufes.vixcourts.entity;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Quadra extends PersistentObjectSupport implements Comparable<Quadra> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private TipoQuadra tipo;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private Double lat;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private Double lng;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private Endereco Target;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToMany(mappedBy="Target")
		private Set<Agendamento> Source;
		
	




	/** Getter for nome. */
	public String getNome() {
		return nome;
	}
	
	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for tipo. */
	public TipoQuadra getTipo() {
		return tipo;
	}
	
	/** Setter for tipo. */
	public void setTipo(TipoQuadra tipo) {
		this.tipo = tipo;
	}

	/** Getter for lat. */
	public Double getLat() {
		return lat;
	}
	
	/** Setter for lat. */
	public void setLat(Double lat) {
		this.lat = lat;
	}

	/** Getter for lng. */
	public Double getLng() {
		return lng;
	}
	
	/** Setter for lng. */
	public void setLng(Double lng) {
		this.lng = lng;
	}




		
		/** Getter for Target. */
		public Endereco getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Endereco Target) {
			this.Target = Target;
		}
		
	

		
		/** Getter for Source. */
		public Set<Agendamento> getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Set<Agendamento> Source) {
			this.Source = Source;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Quadra o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}