package br.inf.ufes.vixcourts.entity;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class SolicitacaoJogo extends PersistentObjectSupport implements Comparable<SolicitacaoJogo> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;






		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private Agendamento Target;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private Usuário Source;
		
	







		
		/** Getter for Target. */
		public Agendamento getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Agendamento Target) {
			this.Target = Target;
		}
		
	

		
		/** Getter for Source. */
		public Usuário getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Usuário Source) {
			this.Source = Source;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(SolicitacaoJogo o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}