package br.inf.ufes.vixcourts.entity;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Time extends PersistentObjectSupport implements Comparable<Time> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String abreviacao;

	/** TODO: generated by FrameWeb. Should be documented. */
	
	private String brasao;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToMany
		private Set<Usuario> Target;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private Usuario Source;
		
	




	/** Getter for nome. */
	public String getNome() {
		return nome;
	}
	
	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for abreviacao. */
	public String getAbreviacao() {
		return abreviacao;
	}
	
	/** Setter for abreviacao. */
	public void setAbreviacao(String abreviacao) {
		this.abreviacao = abreviacao;
	}

	/** Getter for brasao. */
	public String getBrasao() {
		return brasao;
	}
	
	/** Setter for brasao. */
	public void setBrasao(String brasao) {
		this.brasao = brasao;
	}




		
		/** Getter for Target. */
		public Set<Usuario> getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Set<Usuario> Target) {
			this.Target = Target;
		}
		
	

		
		/** Getter for Source. */
		public Usuario getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Usuario Source) {
			this.Source = Source;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Time o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}