package br.inf.ufes.vixcourts.entity;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class UF extends PersistentObjectSupport implements Comparable<UF> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String sigla;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToMany(mappedBy="Target")
		private Set<Cidade> Source;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToOne
		private País Target;
		
	




	/** Getter for nome. */
	public String getNome() {
		return nome;
	}
	
	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for sigla. */
	public String getSigla() {
		return sigla;
	}
	
	/** Setter for sigla. */
	public void setSigla(String sigla) {
		this.sigla = sigla;
	}




		
		/** Getter for Source. */
		public Set<Cidade> getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Set<Cidade> Source) {
			this.Source = Source;
		}
		
	

		
		/** Getter for Target. */
		public País getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(País Target) {
			this.Target = Target;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(UF o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}