package br.inf.ufes.vixcourts.entity;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Usuario extends PersistentObjectSupport implements Comparable<Usuario> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String email;

	/** TODO: generated by FrameWeb. Should be documented. */
	@NotNull
	private String senha;

	/** TODO: generated by FrameWeb. Should be documented. */
	
	private String telefone;

	/** TODO: generated by FrameWeb. Should be documented. */
	
	private String foto;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@ManyToMany(mappedBy="Target")
		private Set<Time> Source;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToMany(mappedBy="Source")
		private Set<Time> Target;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToMany(mappedBy="Source")
		private Set<Agendamento> Target;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToMany(mappedBy="Source")
		private Set<SolicitacaoJogo> Target;
		
	




	/** Getter for nome. */
	public String getNome() {
		return nome;
	}
	
	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for email. */
	public String getEmail() {
		return email;
	}
	
	/** Setter for email. */
	public void setEmail(String email) {
		this.email = email;
	}

	/** Getter for senha. */
	public String getSenha() {
		return senha;
	}
	
	/** Setter for senha. */
	public void setSenha(String senha) {
		this.senha = senha;
	}

	/** Getter for telefone. */
	public String getTelefone() {
		return telefone;
	}
	
	/** Setter for telefone. */
	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	/** Getter for foto. */
	public String getFoto() {
		return foto;
	}
	
	/** Setter for foto. */
	public void setFoto(String foto) {
		this.foto = foto;
	}




		
		/** Getter for Source. */
		public Set<Time> getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Set<Time> Source) {
			this.Source = Source;
		}
		
	

		
		/** Getter for Target. */
		public Set<Time> getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Set<Time> Target) {
			this.Target = Target;
		}
		
	

		
		/** Getter for Target. */
		public Set<Agendamento> getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Set<Agendamento> Target) {
			this.Target = Target;
		}
		
	

		
		/** Getter for Target. */
		public Set<SolicitacaoJogo> getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Set<SolicitacaoJogo> Target) {
			this.Target = Target;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Usuario o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}