package br.inf.ufes.vixcourts.application;

import java.io.Serializable;
import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface agendamentoService extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void salvarAgendamento()();
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void buscarPartidas();
	
}