package br.inf.ufes.vixcourts.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class agendamentoServiceImpl implements agendamentoServiceImpl {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private QuadraDAO quadraDAO;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private AgendamentoDAO agendamentoDAO;
	
	
	

	
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void salvarAgendamento()() {
		// FIXME: auto-generated method stub
		return;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void buscarPartidas() {
		// FIXME: auto-generated method stub
		return;
	}
	
}