package br.inf.ufes.vixcourts.application;

import java.io.Serializable;
import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface agendamentoService extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public boolean salvarAgendamento(Agendamento agendamento);
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Agendamento> buscarPartidas(Modalidade modalidade, Endereco endereco);
	
}