package br.inf.ufes.vixcourts.application;

import java.io.Serializable;
import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface cadastroUsuarioService extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public boolean novoUsuario( usuario);
	
}