package br.inf.ufes.vixcourts.application;

import java.io.Serializable;
import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface quadraService extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public List<Quadra> buscarQuadrasDisponiveis(DateTime HoraInicio, DateTime HoraFim, Endereco Local, TipoQuadra TipoQuadra);
	
}