package br.inf.ufes.vixcourts.application;

import java.io.Serializable;
import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface solicitacaoService extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public boolean solicitarPartida(SolicitacaoJogo solicitacao);
	
}