package br.inf.ufes.vixcourts.application;

import javax.ejb.EJB;
import javax.ejb.Stateless;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class solicitacaoServiceImpl implements solicitacaoServiceImpl {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private SolicitacaoDAO solicitacaoDAO;
	
	
	

	
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void solicitarPartida()() {
		// FIXME: auto-generated method stub
		return;
	}
	
}