package br.inf.ufes.vixcourts.controller;

import javax.ejb.EJB;
import javax.enterprise.inject.*;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class CadastroUsuarioController extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private cadastroUsuarioService cadastroUsuarioService;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Usuario usuario;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private String repetirSenha;
	
	
	
	/** Getter for usuario. */
	public Usuario getUsuario() {
		return usuario;
	}

	/** Setter for usuario. */
	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	
	/** Getter for repetirSenha. */
	public String getRepetirSenha() {
		return repetirSenha;
	}

	/** Setter for repetirSenha. */
	public void setRepetirSenha(String repetirSenha) {
		this.repetirSenha = repetirSenha;
	}
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	public boolean novoUsuario() {
		// FIXME: auto-generated method stub
		return null;
	}
	
}